language: go

go:
 - 1.10.x

os: linux
dist: trusty
sudo: required
services:
- docker
branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

#before_install:
#  - './.travis/main.sh'

script:
  - 'make build'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login https://quay.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make docker ;
    fi  