version: 2
jobs:
  build:
    environment:
      BUILD_NUMBER: ${CIRCLE_BUILD_NUM}
      DOCKER_REGISTRY: quay.io/sheshagiri0
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Sheshagiri/Hello-Go
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make build
          command: make build
      - run:
          name: make docker
          command: |
            docker login -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}  quay.io
            make docker
  master:
    environment:
      BUILD_NUMBER: master
      DOCKER_REGISTRY: quay.io/sheshagiri0
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Sheshagiri/Hello-Go
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make build
          command: make build
      - run:
          name: make docker
          command: |
            docker login -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}  quay.io
            make docker
  release:
    environment:
      RELEASE_TAG: ${CIRCLE_TAG}
      DOCKER_REGISTRY: quay.io/sheshagiri0
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Sheshagiri/Hello-Go
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make build
          command: make build
      - run:
          name: make docker
          command: |
            docker login -u ${QUAY_USERNAME} -p ${QUAY_PASSWORD}  quay.io
            make docker
workflows:
  version: 2
  build-n-release:
    jobs:
      - build:
          filters:  #build all the branches, except master and ignore tags
            tags:
              ignore: /.*/
            branches:
              ignore:
                - master
      - release:
          filters: #build only tags and push the image with tag
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - master:
          filters: #build only master and push the image with master tag
            tags:
              ignore: /.*/
            branches:
              only:
                - master