apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-go-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - hello-go-gateway
  http:
  - route:
    - destination:
        host: hello-go-service